name: Push Operator Docker images to GHCR

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (Optional)'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io  # Setting the registry environment variable

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        driver-opts: image=moby/buildkit:master

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Tag Name
      id: set_tag
      run: echo "::set-output name=tag::${{ github.event.inputs.release_tag || github.sha }}"

    - name: Build and Push Opr Node Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./node/cmd/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/layr-labs/eigenda/opr-node:${{ steps.set_tag.outputs.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Build and Push Opr Plugin Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./node/plugin/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/layr-labs/eigenda/opr-nodeplugin:${{ steps.set_tag.outputs.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Update cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-